### ISSUE TITLE
Failed to upload firmware for ROS2. 

### ISSUE THREAD

**Issue by Geonhee-LEE** [ROBOTIS-GIT/OpenCR-Binaries#1]
Hello.

I am trying to upload firmware to try ROS2.0 using turtlebot3
But, I had a problem when I commanded "./update.sh $OPENCR_PORT $OPENCR_MODEL.opencr"

First, the architecture I tried is arm core. but recognizing the architecture is strange like below. 
![screenshot from 2018-10-16 13-33-01](https://user-images.githubusercontent.com/12562147/47020262-855b3e00-d148-11e8-8034-b952b0651112.png)

After switched the source " shell_cmd="./opencr_ld_shell_x86" into shell_cmd="./opencr_ld_shell_arm", it happened new error like below

![screenshot from 2018-10-16 13-34-04](https://user-images.githubusercontent.com/12562147/47020246-7e343000-d148-11e8-861a-b21295207663.png)

I wonder it is usable for uploading firmware  about ROS2

**Comment by OpusK** [comment]
Hi, @Geonhee-LEE 

Check the execution permission of opencr_ld_shell_arm with the command below.
```bash
$ ls -al
```
If it does not have x permission, use the chmod +x command.
If you still have problems, attach the result of the above command, including the hardware and OS information you are using.

**Comment by Geonhee-LEE** [comment]
Thanks @OpusK 
I authorized the opencr_ld_shell_arm file for execution, but it is same situation , the error is "bash: ./opencr_ld_shell_arm: No such file or directory"
![screenshot from 2018-10-16 14-05-15](https://user-images.githubusercontent.com/12562147/47022252-a02fb180-d14c-11e8-8c65-47d3cf11e301.png)

I tried to build on 

![screenshot from 2018-10-16 14-16-17](https://user-images.githubusercontent.com/12562147/47022979-2ac4e080-d14e-11e8-94c8-57f1b67c5eba.png)
![screenshot from 2018-10-16 14-14-24](https://user-images.githubusercontent.com/12562147/47023022-49c37280-d14e-11e8-9c8d-a66702a2e117.png)

**Comment by OpusK** [comment]
@Geonhee-LEE ,

In the above directory, just run the executable with the following command?
```bash
$ ./opencr_ld_shell_arm
```

**Comment by Geonhee-LEE** [comment]
@OpusK 

I tried both command, which are "./update.sh" and "./opencr_ld_shell_arm" as well.

https://github.com/ROBOTIS-GIT/OpenCR-Binaries/issues/1#issue-370618631

**Comment by OpusK** [comment]
@Geonhee-LEE 

What I was saying is that you have run opencr_ld_shell_arm directly, rather than changing the contents of .sh.
As you can see, the error message is that the system is not looking for the file itself, so I want to check the problem.

+Update: please try [the method of this link](https://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists)
```bash
$ file ./opencr_ld_shell_arm

$ sudo dpkg --add-architecture i386
$ sudo apt-get update
$ sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
```

**Comment by Geonhee-LEE** [comment]
@OpusK  thanks. 

I can't execute the file you said. I got the error message that means "it is not execution file" as I understand.

Anyway, after installing the packages, I will retry to command "./opencr_ld_shell_arm".

regards.

**Comment by OpusK** [comment]
@Geonhee-LEE ,

Has this issue been resolved?

**Comment by OpusK** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by golyalpha** [comment]
I'm having a simmilar issue.
```
ubuntu@turtlebot:~/opencr_update$ ll
total 1224
drwxr-xr-x 2 ubuntu ubuntu   4096 Feb 28 04:24 ./
drwxr-xr-x 9 ubuntu ubuntu   4096 Mar 26 09:57 ../
-rw-r--r-- 1 ubuntu ubuntu 183096 Sep 11  2018 burger.opencr
-rwxr-xr-x 1 ubuntu ubuntu 181808 Sep 11  2018 burger_turtlebot3_core.ino.bin*
-rw-rw-r-- 1 ubuntu ubuntu 211640 Feb 28 04:24 om_with_tb3.opencr
-rwxrwxr-x 1 ubuntu ubuntu 210352 Feb 28 04:22 open_manipulator_turtlebot3_core.ino.bin*
-rwxr-xr-x 1 ubuntu ubuntu  29240 Sep  7  2018 opencr_ld_shell_arm*
-rwxr-xr-x 1 ubuntu ubuntu  38752 Sep  7  2018 opencr_ld_shell_x86*
-rw-r--r-- 1 ubuntu ubuntu      3 Sep  7  2018 released_1.2.5.txt
-rwxr-xr-x 1 ubuntu ubuntu    617 Sep  7  2018 update.sh*
-rw-r--r-- 1 ubuntu ubuntu 183064 Sep 11  2018 waffle.opencr
-rwxr-xr-x 1 ubuntu ubuntu 181776 Sep 11  2018 waffle_turtlebot3_core.ino.bin*
ubuntu@turtlebot:~/opencr_update$ chmod +x opencr_ld_shell_arm
ubuntu@turtlebot:~/opencr_update$ ./opencr_ld_shell_arm
-bash: ./opencr_ld_shell_arm: No such file or directory
```
