### ISSUE TITLE
OpenCR Binary with FastRTPS 1.7.0

### ISSUE THREAD

**Issue by ross-desmond** [ROBOTIS-GIT/OpenCR-Binaries#2]
Following the instructions under http://emanual.robotis.com/docs/en/platform/turtlebot3/applications/
with ROS2 Crystal results in "Error at create session" when attempting to launch the Lidar node on the Turtlebot3. This may to be due to ROS2 Crystal using FastRTPS 1.7.0 and therefore the commit specified in the [install guide ](http://emanual.robotis.com/docs/en/popup/turtlebot3_ros2_sbc_setting/) for micro-xrce-dds-agent must be updated to the latest.

Are there any changes required that update the OpenCR board to work with ROS2 Crystal?

**Comment by OpusK** [comment]
Hi, @ross-desmond 

As described in the manual, did you run the Agent after resetting OpenCR? For OpenCR, this order is very important.

If it does not work in the order in which I was presented, can you give me a detailed description of the order I tested? (Including the ros2, agent version information you are using.)

**Comment by ross-desmond** [comment]
Hi @OpusK 
Thank you for the quick response!
Specs:
Turtlebot3 Burger
ROS2 Crystal

Managed to get it working by following the eprosima install guide with latest eprosima agent:
Previously I followed: http://emanual.robotis.com/docs/en/popup/turtlebot3_ros2_sbc_setting
which ended with "Error at create session."

Seems like it was just that documentation error.

Thanks!

-Ross

**Comment by ross-desmond** [comment]
Please update the eprosima install guide with this [issue](https://github.com/eProsima/Micro-XRCE-DDS-Agent/issues/41) as well. That seems to be blocking multiple turtlebot users with ros2 crystal.

**Comment by ross-desmond** [comment]
Hi @OpusK,

Has ROS2 Crystal been tested on the Turtlebot3 Burger?
[EDIT] I now have ROS2 working on crystal with the following software

Latest ROS2 Crystal from source that includes the following bug:
An issue in ROS2 Crystal which causes a Bus Error on raspberry pi was only fixed 6 days ago: https://github.com/ros2/rcl/issues/363

A merge of the following branches.
[feature/serialdebug](https://github.com/eProsima/Micro-XRCE-DDS-Agent/tree/feature/serialdebug) does not compile with ROS2 Crystal and requires manual merging of the Micro-XRCE-DDS-Agent master/serialdebug branch in order to run the Lidar and OpenCR agents at the same time.

Thank you,

-Ross

**Comment by OpusK** [comment]
Hi, @ross-desmond 

> Has ROS2 Crystal been tested on the Turtlebot3 Burger?

When the Crystal version of ROS2 was released for the first time, I tested it and it worked fine. (According to my E-Manual)

> Latest ROS2 Crystal from source that includes the following bug

If you build in source mode, it seems that some changes can cause problems in behavior.
I will update my ROS2 source again and test it.

> A merge of the following branches.

As you know, I am waiting for eProsima to merge this branch.
In this regard, I will ask them again.
+Update: [MicroXRCEAgent PR](https://github.com/eProsima/Micro-XRCE-DDS-Agent/pull/49)

**Comment by ross-desmond** [comment]
Hi @OpusK,

Completely agree :) just wanted to add this knowledge here for others to see if they try using ROS2 Crystal from source on the Turtlebot3

-Ross

**Comment by OpusK** [comment]
Hi, @ross-desmond.

Thanks for your sharing!
Once this is done, we will update the E-manual.

**Comment by OpusK** [comment]
Hi, @ross-desmond 

I [updated e-manual](https://github.com/ROBOTIS-GIT/emanual/pull/641) today.
Note that when re-installing the agent, remove the "fastrtps" and "fastcdr" installed in sbc.

**Comment by OpusK** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
