### ISSUE TITLE
AARCH64 (ARMv8 64bit) can't run the update script

### ISSUE THREAD

**Issue by golyalpha** [ROBOTIS-GIT/OpenCR-Binaries#4]
I have Ubuntu 18.04 64bit ARM running on my Raspberry Pi. ROS Melodic installed fine and everything built as expected... Untill I got to flashing the OpenCR firmware.

The update.sh script doesn't understand the output of `uname -m` which on 64bit ARMv8s is `aarch64`.
Adding a line, telling it what to do when it meets this architecture name to the update.sh file seems to work fine.

Another issue is, that the opencr_ld_shell_arm binary fails to execute with a "no such file or directory error", even when run directly.
```
ubuntu@turtlebot:~/opencr_update$ file *
burger.opencr:                            SoftQuad DESC or font file binary - version 21845
burger_turtlebot3_core.ino.bin:           data
om_with_tb3.opencr:                       SoftQuad DESC or font file binary - version 21845
open_manipulator_turtlebot3_core.ino.bin: data
opencr_ld_shell_arm:                      ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.2.0, BuildID[sha1]=1de96e9b5a3dc6d6b920f9965565ca6110c2f293, not stripped
opencr_ld_shell_x86:                      ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=c2c09c958b1e2ea4b6aeff88757e198ce7b69ab8, not stripped
released_1.2.5.txt:                       ASCII text
update.sh:                                Bourne-Again shell script, ASCII text executable
waffle.opencr:                            SoftQuad DESC or font file binary - version 21845
waffle_turtlebot3_core.ino.bin:           data
```
Could be because it's a 32bit ARMv7 executable and I'm trying to run it on a 64bit ARMv8, in which case, it might be apropriate to rebuild that executable for AARCH64, since that's what's on the RPi3 that I got with Turtlebot 3.

**Comment by OpusK** [comment]
Hi, @golyalpha 

I'm sorry for late reply.
I updated [the script](https://github.com/ROBOTIS-GIT/OpenCR-Binaries/blob/master/turtlebot3/ROS2/latest/opencr_update/update.sh#L10) to support aarch64.

However, since the executable file is a 32-bit executable file, the following dependency must be installed in the aarch64 OS.

```bash
$ sudo dpkg --add-architecture armhf
$ sudo apt-get update
$ sudo apt-get install libc6:armhf
```

+Add: Oh, I didn't update the ROS1 file... I will update soon :)

**Comment by golyalpha** [comment]
Awesome. Unfortunately I can't verify that it works on the RPi right now, since the robot is stuck in a lab I won't have access to for the next month... I might be able to try it on another board which also has an ARMv8 64bit chip, Rock64 (by pine64.org), is that worth it?

**Comment by OpusK** [comment]
I tested it on the RPi3 B+ model.
And this is currently applied in TB3 ROS2.
You can try it when you need it :)

**Comment by artivis** [comment]
I hit the same issue with the same setup. I can confirm that updating the script and installing `libc6:armhf` fixed the issue and I could run `update.sh` successfully!  
Thanks.

**Comment by KyoungHwan2046** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
